/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v10.0
processor: MK64FX512xxx12
package_id: MK64FX512VLL12
mcu_data: ksdk2_0
processor_version: 10.0.0
pin_labels:
- {pin_num: '62', pin_signal: PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/EWM_IN, label: RST_ETH, identifier: RST_ETH}
- {pin_num: '57', pin_signal: PTB9/SPI1_PCS1/UART3_CTS_b/FB_AD20, label: CDE_LUM_ZONE_2, identifier: LUMINOSITE_IN;CDE_LUM_ZONE_2}
- {pin_num: '94', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, label: SPI0_SCK, identifier: SPI0_CS;SPI0_SCK}
- {pin_num: '93', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, label: SPI0_CS, identifier: SPI0_SCK;SPI0_CS}
- {pin_num: '55', pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/ENET0_1588_TMR0/FTM0_FLT3, label: CDE_LUM_ZONE_3, identifier: RELAY_1;COM_LUM_ZONE;CDE_LUM_ZONE_3}
- {pin_num: '56', pin_signal: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/FTM0_FLT0, label: CDE_LUM_ZONE_2, identifier: RELAY_2;CDE_LUM_ZONE_3;CDE_LUM_ZONE_2}
- {pin_num: '92', pin_signal: PTC18/UART3_RTS_b/ENET0_1588_TMR2/FB_TBST_b/FB_CS2_b/FB_BE15_8_BLS23_16_b, label: UART0_BREAK_DETECT_IN, identifier: UART_BREAK_DETECT_IN;UART0_BREAK_DETECT_IN}
- {pin_num: '97', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FB_AD2/EWM_IN/SPI1_PCS0, label: RS485_RTS, identifier: RS485_RTS_PIN;RS485_RTS}
- {pin_num: '100', pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/FTM0_FLT1/SPI1_SIN, label: UART0_TX_OUTPUT, identifier: UART0_TX_OUTPUT}
- {pin_num: '58', pin_signal: ADC1_SE14/PTB10/SPI1_PCS0/UART3_RX/FB_AD19/FTM0_FLT1, label: CDE_LUM_ZONE_1, identifier: CDE_LUM_ZONE_1}
- {pin_num: '59', pin_signal: ADC1_SE15/PTB11/SPI1_SCK/UART3_TX/FB_AD18/FTM0_FLT2, label: REG_LUM_GEN, identifier: REG_LUM_GEN}
- {pin_num: '86', pin_signal: PTC14/UART4_RX/FB_AD25, label: LUM_GEN, identifier: LUM_GEN}
- {pin_num: '87', pin_signal: PTC15/UART4_TX/FB_AD24, label: LUM_ZONE_1, identifier: LUM_ZONE_1}
- {pin_num: '90', pin_signal: PTC16/UART3_RX/ENET0_1588_TMR0/FB_CS5_b/FB_TSIZ1/FB_BE23_16_BLS15_8_b, label: LUM_ZONE_2, identifier: LUM_ZONE_2}
- {pin_num: '91', pin_signal: PTC17/UART3_TX/ENET0_1588_TMR1/FB_CS4_b/FB_TSIZ0/FB_BE31_24_BLS7_0_b, label: LUM_ZONE_3, identifier: LUM_ZONE_3}
- {pin_num: '65', pin_signal: PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB, label: LUM_PWM, identifier: LUM_GEN_ZONE;LUM_ENABLE;LUM_PWM}
- {pin_num: '64', pin_signal: PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/FTM2_QD_PHA, label: MOTOR_CLK, identifier: MOTOR_CLK}
- {pin_num: '70', pin_signal: ADC0_SE14/PTC0/SPI0_PCS4/PDB0_EXTRG/USB_SOF_OUT/FB_AD14/I2S0_TXD1, label: MOTOR_YELLOW, identifier: MOTOR_YELLOW}
- {pin_num: '71', pin_signal: ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/I2S0_TXD0, label: MOTOR_RED, identifier: MOTOR_RED}
- {pin_num: '72', pin_signal: ADC0_SE4b/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FB_AD12/I2S0_TX_FS, label: MOTOR_BLUE, identifier: MOTOR_BLUE}
- {pin_num: '73', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK, label: MOTOR_ORANGE, identifier: MOTOR_ORANGE}
- {pin_num: '68', pin_signal: PTB22/SPI2_SOUT/FB_AD29/CMP2_OUT, label: VOLTMETRE_VOIE, identifier: VOLTMETRE_VOIE}
- {pin_num: '69', pin_signal: PTB23/SPI2_SIN/SPI0_PCS5/FB_AD28, label: VOLTMETRE_READ_BASCULE, identifier: VOLTMETRE_READ_BASCULE}
- {pin_num: '98', pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FB_AD1/EWM_OUT_b/SPI1_SCK, label: VOLTMETRE_INPUT_CAPTURE, identifier: VOLTMETRE_INPUT_CAPTURE}
- {pin_num: '1', pin_signal: ADC1_SE4a/PTE0/SPI1_PCS1/UART1_TX/SDHC0_D1/TRACE_CLKOUT/I2C1_SDA/RTC_CLKOUT, label: DEBUG_PORT_E0, identifier: DEBUG_PORT_E0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '95', peripheral: SPI0, signal: SOUT, pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/I2C0_SCL}
  - {pin_num: '94', peripheral: SPI0, signal: SCK, pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, identifier: SPI0_SCK, direction: OUTPUT}
  - {pin_num: '93', peripheral: SPI0, signal: PCS0_SS, pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, identifier: SPI0_CS, direction: OUTPUT,
    open_drain: enable}
  - {pin_num: '83', peripheral: I2C1, signal: SDA, pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/I2S0_RXD1/FB_RW_b, open_drain: enable}
  - {pin_num: '82', peripheral: I2C1, signal: SCL, pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5, open_drain: enable}
  - {pin_num: '62', peripheral: GPIOB, signal: 'GPIO, 16', pin_signal: PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/EWM_IN, direction: OUTPUT, gpio_init_state: 'true',
    drive_strength: low}
  - {pin_num: '55', peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/ENET0_1588_TMR0/FTM0_FLT3, identifier: CDE_LUM_ZONE_3, direction: INPUT,
    gpio_interrupt: no_init, open_drain: enable}
  - {pin_num: '56', peripheral: GPIOB, signal: 'GPIO, 3', pin_signal: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/FTM0_FLT0, identifier: CDE_LUM_ZONE_2,
    direction: INPUT, gpio_interrupt: no_init, open_drain: enable}
  - {pin_num: '39', peripheral: ENET, signal: RMII_RXER, pin_signal: PTA5/USB_CLKIN/FTM0_CH2/RMII0_RXER/MII0_RXER/CMP2_OUT/I2S0_TX_BCLK/JTAG_TRST_b}
  - {pin_num: '46', peripheral: ENET, signal: RMII_TXD0, pin_signal: PTA16/SPI0_SOUT/UART0_CTS_b/UART0_COL_b/RMII0_TXD0/MII0_TXD0/I2S0_RX_FS/I2S0_RXD1}
  - {pin_num: '47', peripheral: ENET, signal: RMII_TXD1, pin_signal: ADC1_SE17/PTA17/SPI0_SIN/UART0_RTS_b/RMII0_TXD1/MII0_TXD1/I2S0_MCLK}
  - {pin_num: '45', peripheral: ENET, signal: RMII_TXEN, pin_signal: PTA15/SPI0_SCK/UART0_RX/RMII0_TXEN/MII0_TXEN/I2S0_RXD0}
  - {pin_num: '44', peripheral: ENET, signal: RMII_CRS_DV, pin_signal: PTA14/SPI0_PCS0/UART0_TX/RMII0_CRS_DV/MII0_RXDV/I2C2_SCL/I2S0_RX_BCLK/I2S0_TXD1}
  - {pin_num: '43', peripheral: ENET, signal: RMII_RXD0, pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/RMII0_RXD0/MII0_RXD0/I2C2_SDA/I2S0_TX_FS/FTM1_QD_PHB}
  - {pin_num: '42', peripheral: ENET, signal: RMII_RXD1, pin_signal: CMP2_IN0/PTA12/CAN0_TX/FTM1_CH0/RMII0_RXD1/MII0_RXD1/I2C2_SCL/I2S0_TXD0/FTM1_QD_PHA}
  - {pin_num: '53', peripheral: ENET, signal: RMII_MDIO, pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/RMII0_MDIO/MII0_MDIO/FTM1_QD_PHA}
  - {pin_num: '54', peripheral: ENET, signal: RMII_MDC, pin_signal: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/FTM1_QD_PHB}
  - {pin_num: '50', peripheral: ENET, signal: RMII_CLKIN, pin_signal: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0}
  - {pin_num: '92', peripheral: GPIOC, signal: 'GPIO, 18', pin_signal: PTC18/UART3_RTS_b/ENET0_1588_TMR2/FB_TBST_b/FB_CS2_b/FB_BE15_8_BLS23_16_b, identifier: UART0_BREAK_DETECT_IN,
    direction: INPUT, gpio_interrupt: no_init, open_drain: enable}
  - {pin_num: '99', peripheral: UART0, signal: RX, pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FB_AD0/FTM0_FLT0/SPI1_SOUT}
  - {pin_num: '100', peripheral: UART0, signal: TX, pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/FTM0_FLT1/SPI1_SIN, direction: OUTPUT}
  - {pin_num: '97', peripheral: UART0, signal: RTS, pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FB_AD2/EWM_IN/SPI1_PCS0}
  - {pin_num: '58', peripheral: GPIOB, signal: 'GPIO, 10', pin_signal: ADC1_SE14/PTB10/SPI1_PCS0/UART3_RX/FB_AD19/FTM0_FLT1, direction: INPUT, gpio_interrupt: no_init,
    open_drain: enable}
  - {pin_num: '59', peripheral: GPIOB, signal: 'GPIO, 11', pin_signal: ADC1_SE15/PTB11/SPI1_SCK/UART3_TX/FB_AD18/FTM0_FLT2, direction: INPUT, gpio_interrupt: no_init}
  - {pin_num: '96', peripheral: SPI0, signal: SIN, pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/I2C0_SDA}
  - {pin_num: '91', peripheral: GPIOC, signal: 'GPIO, 17', pin_signal: PTC17/UART3_TX/ENET0_1588_TMR1/FB_CS4_b/FB_TSIZ0/FB_BE31_24_BLS7_0_b, direction: OUTPUT, gpio_init_state: 'true',
    open_drain: enable}
  - {pin_num: '90', peripheral: GPIOC, signal: 'GPIO, 16', pin_signal: PTC16/UART3_RX/ENET0_1588_TMR0/FB_CS5_b/FB_TSIZ1/FB_BE23_16_BLS15_8_b, direction: OUTPUT}
  - {pin_num: '87', peripheral: GPIOC, signal: 'GPIO, 15', pin_signal: PTC15/UART4_TX/FB_AD24, direction: OUTPUT}
  - {pin_num: '86', peripheral: GPIOC, signal: 'GPIO, 14', pin_signal: PTC14/UART4_RX/FB_AD25, direction: OUTPUT}
  - {pin_num: '68', peripheral: GPIOB, signal: 'GPIO, 22', pin_signal: PTB22/SPI2_SOUT/FB_AD29/CMP2_OUT, direction: OUTPUT}
  - {pin_num: '69', peripheral: GPIOB, signal: 'GPIO, 23', pin_signal: PTB23/SPI2_SIN/SPI0_PCS5/FB_AD28, direction: INPUT}
  - {pin_num: '65', peripheral: FTM2, signal: 'CH, 1', pin_signal: PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB, identifier: LUM_PWM, direction: OUTPUT}
  - {pin_num: '64', peripheral: FTM2, signal: 'CH, 0', pin_signal: PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/FTM2_QD_PHA, direction: OUTPUT}
  - {pin_num: '70', peripheral: GPIOC, signal: 'GPIO, 0', pin_signal: ADC0_SE14/PTC0/SPI0_PCS4/PDB0_EXTRG/USB_SOF_OUT/FB_AD14/I2S0_TXD1, direction: OUTPUT}
  - {pin_num: '71', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/I2S0_TXD0, direction: OUTPUT}
  - {pin_num: '72', peripheral: GPIOC, signal: 'GPIO, 2', pin_signal: ADC0_SE4b/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FB_AD12/I2S0_TX_FS, direction: OUTPUT}
  - {pin_num: '73', peripheral: GPIOC, signal: 'GPIO, 3', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK, direction: OUTPUT}
  - {pin_num: '98', peripheral: FTM0, signal: 'CH, 5', pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FB_AD1/EWM_OUT_b/SPI1_SCK, direction: INPUT}
  - {pin_num: '1', peripheral: GPIOE, signal: 'GPIO, 0', pin_signal: ADC1_SE4a/PTE0/SPI1_PCS1/UART1_TX/SDHC0_D1/TRACE_CLKOUT/I2C1_SDA/RTC_CLKOUT, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t CDE_LUM_ZONE_3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB2 (pin 55)  */
    GPIO_PinInit(BOARD_INITPINS_CDE_LUM_ZONE_3_GPIO, BOARD_INITPINS_CDE_LUM_ZONE_3_PIN, &CDE_LUM_ZONE_3_config);

    gpio_pin_config_t CDE_LUM_ZONE_2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB3 (pin 56)  */
    GPIO_PinInit(BOARD_INITPINS_CDE_LUM_ZONE_2_GPIO, BOARD_INITPINS_CDE_LUM_ZONE_2_PIN, &CDE_LUM_ZONE_2_config);

    gpio_pin_config_t CDE_LUM_ZONE_1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB10 (pin 58)  */
    GPIO_PinInit(BOARD_INITPINS_CDE_LUM_ZONE_1_GPIO, BOARD_INITPINS_CDE_LUM_ZONE_1_PIN, &CDE_LUM_ZONE_1_config);

    gpio_pin_config_t REG_LUM_GEN_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB11 (pin 59)  */
    GPIO_PinInit(BOARD_INITPINS_REG_LUM_GEN_GPIO, BOARD_INITPINS_REG_LUM_GEN_PIN, &REG_LUM_GEN_config);

    gpio_pin_config_t RST_ETH_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB16 (pin 62)  */
    GPIO_PinInit(BOARD_INITPINS_RST_ETH_GPIO, BOARD_INITPINS_RST_ETH_PIN, &RST_ETH_config);

    gpio_pin_config_t VOLTMETRE_VOIE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB22 (pin 68)  */
    GPIO_PinInit(BOARD_INITPINS_VOLTMETRE_VOIE_GPIO, BOARD_INITPINS_VOLTMETRE_VOIE_PIN, &VOLTMETRE_VOIE_config);

    gpio_pin_config_t VOLTMETRE_READ_BASCULE_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB23 (pin 69)  */
    GPIO_PinInit(BOARD_INITPINS_VOLTMETRE_READ_BASCULE_GPIO, BOARD_INITPINS_VOLTMETRE_READ_BASCULE_PIN, &VOLTMETRE_READ_BASCULE_config);

    gpio_pin_config_t MOTOR_YELLOW_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC0 (pin 70)  */
    GPIO_PinInit(BOARD_INITPINS_MOTOR_YELLOW_GPIO, BOARD_INITPINS_MOTOR_YELLOW_PIN, &MOTOR_YELLOW_config);

    gpio_pin_config_t MOTOR_RED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC1 (pin 71)  */
    GPIO_PinInit(BOARD_INITPINS_MOTOR_RED_GPIO, BOARD_INITPINS_MOTOR_RED_PIN, &MOTOR_RED_config);

    gpio_pin_config_t MOTOR_BLUE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC2 (pin 72)  */
    GPIO_PinInit(BOARD_INITPINS_MOTOR_BLUE_GPIO, BOARD_INITPINS_MOTOR_BLUE_PIN, &MOTOR_BLUE_config);

    gpio_pin_config_t MOTOR_ORANGE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC3 (pin 73)  */
    GPIO_PinInit(BOARD_INITPINS_MOTOR_ORANGE_GPIO, BOARD_INITPINS_MOTOR_ORANGE_PIN, &MOTOR_ORANGE_config);

    gpio_pin_config_t LUM_GEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC14 (pin 86)  */
    GPIO_PinInit(BOARD_INITPINS_LUM_GEN_GPIO, BOARD_INITPINS_LUM_GEN_PIN, &LUM_GEN_config);

    gpio_pin_config_t LUM_ZONE_1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC15 (pin 87)  */
    GPIO_PinInit(BOARD_INITPINS_LUM_ZONE_1_GPIO, BOARD_INITPINS_LUM_ZONE_1_PIN, &LUM_ZONE_1_config);

    gpio_pin_config_t LUM_ZONE_2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC16 (pin 90)  */
    GPIO_PinInit(BOARD_INITPINS_LUM_ZONE_2_GPIO, BOARD_INITPINS_LUM_ZONE_2_PIN, &LUM_ZONE_2_config);

    gpio_pin_config_t LUM_ZONE_3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC17 (pin 91)  */
    GPIO_PinInit(BOARD_INITPINS_LUM_ZONE_3_GPIO, BOARD_INITPINS_LUM_ZONE_3_PIN, &LUM_ZONE_3_config);

    gpio_pin_config_t UART0_BREAK_DETECT_IN_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC18 (pin 92)  */
    GPIO_PinInit(BOARD_INITPINS_UART0_BREAK_DETECT_IN_GPIO, BOARD_INITPINS_UART0_BREAK_DETECT_IN_PIN, &UART0_BREAK_DETECT_IN_config);

    gpio_pin_config_t DEBUG_PORT_E0_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE0 (pin 1)  */
    GPIO_PinInit(BOARD_INITPINS_DEBUG_PORT_E0_GPIO, BOARD_INITPINS_DEBUG_PORT_E0_PIN, &DEBUG_PORT_E0_config);

    /* PORTA12 (pin 42) is configured as RMII0_RXD1 */
    PORT_SetPinMux(PORTA, 12U, kPORT_MuxAlt4);

    /* PORTA13 (pin 43) is configured as RMII0_RXD0 */
    PORT_SetPinMux(PORTA, 13U, kPORT_MuxAlt4);

    /* PORTA14 (pin 44) is configured as RMII0_CRS_DV */
    PORT_SetPinMux(PORTA, 14U, kPORT_MuxAlt4);

    /* PORTA15 (pin 45) is configured as RMII0_TXEN */
    PORT_SetPinMux(PORTA, 15U, kPORT_MuxAlt4);

    /* PORTA16 (pin 46) is configured as RMII0_TXD0 */
    PORT_SetPinMux(PORTA, 16U, kPORT_MuxAlt4);

    /* PORTA17 (pin 47) is configured as RMII0_TXD1 */
    PORT_SetPinMux(PORTA, 17U, kPORT_MuxAlt4);

    /* PORTA18 (pin 50) is configured as EXTAL0 */
    PORT_SetPinMux(PORTA, 18U, kPORT_PinDisabledOrAnalog);

    /* PORTA5 (pin 39) is configured as RMII0_RXER */
    PORT_SetPinMux(PORTA, 5U, kPORT_MuxAlt4);

    /* PORTB0 (pin 53) is configured as RMII0_MDIO */
    PORT_SetPinMux(PORTB, 0U, kPORT_MuxAlt4);

    /* PORTB1 (pin 54) is configured as RMII0_MDC */
    PORT_SetPinMux(PORTB, 1U, kPORT_MuxAlt4);

    /* PORTB10 (pin 58) is configured as PTB10 */
    PORT_SetPinMux(BOARD_INITPINS_CDE_LUM_ZONE_1_PORT, BOARD_INITPINS_CDE_LUM_ZONE_1_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[10] = ((PORTB->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTB11 (pin 59) is configured as PTB11 */
    PORT_SetPinMux(BOARD_INITPINS_REG_LUM_GEN_PORT, BOARD_INITPINS_REG_LUM_GEN_PIN, kPORT_MuxAsGpio);

    /* PORTB16 (pin 62) is configured as PTB16 */
    PORT_SetPinMux(BOARD_INITPINS_RST_ETH_PORT, BOARD_INITPINS_RST_ETH_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[16] = ((PORTB->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Drive Strength Enable: Low drive strength is configured on the corresponding pin, if pin
                       * is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_LowDriveStrength));

    /* PORTB18 (pin 64) is configured as FTM2_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_MOTOR_CLK_PORT, BOARD_INITPINS_MOTOR_CLK_PIN, kPORT_MuxAlt3);

    /* PORTB19 (pin 65) is configured as FTM2_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_LUM_PWM_PORT, BOARD_INITPINS_LUM_PWM_PIN, kPORT_MuxAlt3);

    /* PORTB2 (pin 55) is configured as PTB2 */
    PORT_SetPinMux(BOARD_INITPINS_CDE_LUM_ZONE_3_PORT, BOARD_INITPINS_CDE_LUM_ZONE_3_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[2] = ((PORTB->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTB22 (pin 68) is configured as PTB22 */
    PORT_SetPinMux(BOARD_INITPINS_VOLTMETRE_VOIE_PORT, BOARD_INITPINS_VOLTMETRE_VOIE_PIN, kPORT_MuxAsGpio);

    /* PORTB23 (pin 69) is configured as PTB23 */
    PORT_SetPinMux(BOARD_INITPINS_VOLTMETRE_READ_BASCULE_PORT, BOARD_INITPINS_VOLTMETRE_READ_BASCULE_PIN, kPORT_MuxAsGpio);

    /* PORTB3 (pin 56) is configured as PTB3 */
    PORT_SetPinMux(BOARD_INITPINS_CDE_LUM_ZONE_2_PORT, BOARD_INITPINS_CDE_LUM_ZONE_2_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[3] = ((PORTB->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTC0 (pin 70) is configured as PTC0 */
    PORT_SetPinMux(BOARD_INITPINS_MOTOR_YELLOW_PORT, BOARD_INITPINS_MOTOR_YELLOW_PIN, kPORT_MuxAsGpio);

    /* PORTC1 (pin 71) is configured as PTC1 */
    PORT_SetPinMux(BOARD_INITPINS_MOTOR_RED_PORT, BOARD_INITPINS_MOTOR_RED_PIN, kPORT_MuxAsGpio);

    /* PORTC10 (pin 82) is configured as I2C1_SCL */
    PORT_SetPinMux(PORTC, 10U, kPORT_MuxAlt2);

    PORTC->PCR[10] = ((PORTC->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTC11 (pin 83) is configured as I2C1_SDA */
    PORT_SetPinMux(PORTC, 11U, kPORT_MuxAlt2);

    PORTC->PCR[11] = ((PORTC->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTC14 (pin 86) is configured as PTC14 */
    PORT_SetPinMux(BOARD_INITPINS_LUM_GEN_PORT, BOARD_INITPINS_LUM_GEN_PIN, kPORT_MuxAsGpio);

    /* PORTC15 (pin 87) is configured as PTC15 */
    PORT_SetPinMux(BOARD_INITPINS_LUM_ZONE_1_PORT, BOARD_INITPINS_LUM_ZONE_1_PIN, kPORT_MuxAsGpio);

    /* PORTC16 (pin 90) is configured as PTC16 */
    PORT_SetPinMux(BOARD_INITPINS_LUM_ZONE_2_PORT, BOARD_INITPINS_LUM_ZONE_2_PIN, kPORT_MuxAsGpio);

    /* PORTC17 (pin 91) is configured as PTC17 */
    PORT_SetPinMux(BOARD_INITPINS_LUM_ZONE_3_PORT, BOARD_INITPINS_LUM_ZONE_3_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[17] = ((PORTC->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTC18 (pin 92) is configured as PTC18 */
    PORT_SetPinMux(BOARD_INITPINS_UART0_BREAK_DETECT_IN_PORT, BOARD_INITPINS_UART0_BREAK_DETECT_IN_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[18] = ((PORTC->PCR[18] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTC2 (pin 72) is configured as PTC2 */
    PORT_SetPinMux(BOARD_INITPINS_MOTOR_BLUE_PORT, BOARD_INITPINS_MOTOR_BLUE_PIN, kPORT_MuxAsGpio);

    /* PORTC3 (pin 73) is configured as PTC3 */
    PORT_SetPinMux(BOARD_INITPINS_MOTOR_ORANGE_PORT, BOARD_INITPINS_MOTOR_ORANGE_PIN, kPORT_MuxAsGpio);

    /* PORTD0 (pin 93) is configured as SPI0_PCS0 */
    PORT_SetPinMux(BOARD_INITPINS_SPI0_CS_PORT, BOARD_INITPINS_SPI0_CS_PIN, kPORT_MuxAlt2);

    PORTD->PCR[0] = ((PORTD->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTD1 (pin 94) is configured as SPI0_SCK */
    PORT_SetPinMux(BOARD_INITPINS_SPI0_SCK_PORT, BOARD_INITPINS_SPI0_SCK_PIN, kPORT_MuxAlt2);

    /* PORTD2 (pin 95) is configured as SPI0_SOUT */
    PORT_SetPinMux(PORTD, 2U, kPORT_MuxAlt2);

    /* PORTD3 (pin 96) is configured as SPI0_SIN */
    PORT_SetPinMux(PORTD, 3U, kPORT_MuxAlt2);

    /* PORTD4 (pin 97) is configured as UART0_RTS_b */
    PORT_SetPinMux(PORTD, 4U, kPORT_MuxAlt3);

    /* PORTD5 (pin 98) is configured as FTM0_CH5 */
    PORT_SetPinMux(BOARD_INITPINS_VOLTMETRE_INPUT_CAPTURE_PORT, BOARD_INITPINS_VOLTMETRE_INPUT_CAPTURE_PIN, kPORT_MuxAlt4);

    /* PORTD6 (pin 99) is configured as UART0_RX */
    PORT_SetPinMux(PORTD, 6U, kPORT_MuxAlt3);

    /* PORTD7 (pin 100) is configured as UART0_TX */
    PORT_SetPinMux(BOARD_INITPINS_UART0_TX_OUTPUT_PORT, BOARD_INITPINS_UART0_TX_OUTPUT_PIN, kPORT_MuxAlt3);

    /* PORTE0 (pin 1) is configured as PTE0 */
    PORT_SetPinMux(BOARD_INITPINS_DEBUG_PORT_E0_PORT, BOARD_INITPINS_DEBUG_PORT_E0_PIN, kPORT_MuxAsGpio);

    SIM->SOPT2 = ((SIM->SOPT2 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT2_RMIISRC_MASK)))

                  /* RMII clock source select: EXTAL clock. */
                  | SIM_SOPT2_RMIISRC(SOPT2_RMIISRC_EXTAL));

    SIM->SOPT4 = ((SIM->SOPT4 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT4_FTM2CH0SRC_MASK)))

                  /* FTM2 channel 0 input capture source select: FTM2_CH0 signal. */
                  | SIM_SOPT4_FTM2CH0SRC(SOPT4_FTM2CH0SRC_FTM));

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART0TXSRC_MASK)))

                  /* UART 0 transmit data source select: UART0_TX pin. */
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
